version: "3.9"

services:
  blog:
    ports:
      - "9000:8080"
    restart: always
    build:
      context: ../..
      dockerfile: deployments/docker/blog/Dockerfile
    depends_on:
      - db
    container_name: blog
    environment:
      - KAFKA_URL=kafka:9092
      - KAFKA_TOPIC=created.post
      - CONFIG_PATH=./configs/local.yaml
      - DATABASE_USER=vladislav
      - DATABASE_PASSWORD=456
      - DATABASE_NAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

  db:
    image: postgres:alpine
    restart: always
    container_name: db_project
    environment:
      - POSTGRES_USER=vladislav
      - POSTGRES_PASSWORD=456
      - POSTGRES_DB=postgres
    ports:
      - "5444:5432"
    volumes:
      - ../../data:/var/lib/postgresql/data
  kafka:
    image: confluentinc/cp-kafka:7.6.0.amd64
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,COMPOSE:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka:29092,CONTROLLER://kafka:29093,COMPOSE://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,COMPOSE://kafka:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka-data:/var/lib/kafka/data
volumes:
  kafka-data: